logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG

api:
  external:
    book-reader-books-api:
      name: book-reader-books-api
      url: ${BOOKS_URL:localhost:8080/books/}
      endpoint: {id}

full-path: ${api.external.book-reader-books-api.url}${api.external.book-reader-books-api.endpoint}

server:
  port: 8084